# Generated by Django 5.2.17 on 2026-09-02 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dodo_product_id', models.CharField(blank=True, max_length=128)),
                ('dodo_seat_addon_id', models.CharField(blank=True, max_length=128)),
                ('included_seats', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(default=dict)),
                ('included_quotas', models.JSONField(default=dict)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DodoWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dodo_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='free', max_length=32)),
                ('dodo_customer_id', models.CharField(blank=True, max_length=128)),
                ('dodo_subscription_id', models.CharField(blank=True, max_length=128)),
                ('extra_seats', models.PositiveIntegerField(default=0)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingplan')),
            ],
            options={
                'db_table': 'organization_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter', models.CharField(max_length=64)),
                ('period_start', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='accounts.organization')),
            ],
            options={
                'db_table': 'billing_usage_counters',
                'constraints': [models.UniqueConstraint(fields=('organization', 'meter', 'period_start'), name='uniq_usage_org_meter_period')],
            },
        ),
        migrations.CreateModel(
            name='UsageEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='usage_outbox', to='accounts.organization')),
            ],
            options={
                'db_table': 'billing_usage_outbox',
                'indexes': [models.Index(fields=['ingested_at', 'created_at'], name='idx_usage_outbox_pending')],
            },
        ),
    ]
