# Generated by Django 5.2.17 on 2026-09-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('billing', '0002_paymentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentprofile',
            name='organization',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='accounts.organization'),
        ),
    ]
