# Generated by Django 5.2.17 on 2026-09-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('billing', '0003_remove_paymentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='organization',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='accounts.organization'),
        ),
    ]
