# Generated by Django 5.2.17 on 2026-09-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_paymentprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='dodo_price_id_monthly',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='dodo_price_id_yearly',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='price_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='price_yearly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_billing_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='billing.billingplan'),
        ),
    ]
