# Generated by Django 5.2.17 on 2026-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingplan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='extra_seat_price_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='extra_seat_price_yearly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='included_wa_accounts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
