# Generated by Django 5.2.17 on 2026-09-29 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodoProductSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.PositiveIntegerField()),
                ('sync_key', models.CharField(max_length=255, unique=True)),
                ('dodo_product_id', models.CharField(blank=True, max_length=128)),
                ('dodo_price_id', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=16)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodo_product_syncs', to='billing.billingplan')),
            ],
            options={
                'db_table': 'billing_dodo_product_syncs',
                'ordering': ['plan__display_order', 'plan__key', 'interval'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'interval', 'currency', 'amount'), name='uniq_dodo_product_sync_plan_interval_amount')],
            },
        ),
    ]
